import express from 'express';
import cookieParser from 'cookie-parser';
import helmet from 'helmet';
import { rateLimit } from 'express-rate-limit';
import { z } from 'zod';
import { query, withContext, healthcheck, cleanupExpired } from './db.js';
import { randomToken,tokenHash,familyCode,normalizeEmail,normalizeFamilyCode,normalizeNickname,nicknameIsSafe,hashPassword,verifyPassword,hashPin,verifyPin,constantTimeEqual } from './security.js';
import { mailerReady, sendVerificationEmail, sendPasswordResetEmail } from './mailer.js';
import { childSafeReply } from './ai.js';

const app=express();
const port=Number(process.env.PORT||3000);
const production=process.env.NODE_ENV==='production';
const publicOrigin=(process.env.PUBLIC_ORIGIN||'http://localhost:8080').replace(/\/$/,'');
const PC='parent_session',CC='child_session',PX='parent_csrf',CX='child_csrf';
if(production&&(!process.env.SESSION_PEPPER||!process.env.PIN_PEPPER||!process.env.DB_PASSWORD)) throw new Error('Missing production secrets');
app.set('trust proxy',1);app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:false,crossOriginResourcePolicy:false}));app.use(express.json({limit:'16kb',strict:true}));app.use(cookieParser());
const limiter=rateLimit({windowMs:60_000,limit:120,standardHeaders:'draft-8',legacyHeaders:false});
const authLimiter=rateLimit({windowMs:15*60_000,limit:15,standardHeaders:'draft-8',legacyHeaders:false});
const childLimiter=rateLimit({windowMs:60*60_000,limit:8,standardHeaders:'draft-8',legacyHeaders:false});
const chatLimiter=rateLimit({windowMs:60_000,limit:12,standardHeaders:'draft-8',legacyHeaders:false});
app.use('/api',limiter);
function fail(res,status,code){return res.status(status).json({ok:false,code});}
function copt(ms,httpOnly=true){return{httpOnly,secure:production,sameSite:'strict',path:'/',maxAge:ms};}
app.use('/api',(req,res,next)=>{if(!['POST','PUT','PATCH','DELETE'].includes(req.method))return next();const origin=req.get('origin'),site=req.get('sec-fetch-site');if(production&&origin&&origin!==publicOrigin)return fail(res,403,'origin_forbidden');if(production&&site==='cross-site')return fail(res,403,'cross_site_forbidden');next();});
async function createSession(type,res,parentId=null,childId=null){const token=randomToken(),csrf=randomToken(18),parent=type==='parent',ms=parent?7*86400000:86400000;await query(`INSERT INTO sessions(session_type,parent_id,child_id,token_hash,expires_at) VALUES($1,$2,$3,$4,$5)`,[type,parentId,childId,tokenHash(token),new Date(Date.now()+ms)]);res.cookie(parent?PC:CC,token,copt(ms,true));res.cookie(parent?PX:CX,csrf,copt(ms,false));}
async function session(req,type){const token=req.cookies[type==='parent'?PC:CC];if(!token)return null;const r=await query(`SELECT s.id,s.parent_id,s.child_id,p.email,p.verified_at,p.family_code,p.marketing_opt_in FROM sessions s LEFT JOIN parents p ON p.id=s.parent_id WHERE s.session_type=$1 AND s.token_hash=$2 AND s.expires_at>NOW() LIMIT 1`,[type,tokenHash(token)]),row=r.rows[0];if(!row)return null;if(type==='child'&&row.child_id){const child=await withContext({childId:row.child_id},async c=>(await c.query('SELECT nickname,age_group,hero,status,ai_enabled FROM children WHERE id=$1',[row.child_id])).rows[0]);if(!child)return null;return{...row,...child}}return row;}
function csrf(type){return(req,res,next)=>{const n=type==='parent'?PX:CX,c=req.cookies[n],h=req.get('x-csrf-token');if(!c||!h||!constantTimeEqual(c,h))return fail(res,403,'csrf_failed');next();};}
async function parentAuth(req,res,next){try{const s=await session(req,'parent');if(!s?.parent_id)return fail(res,401,'parent_auth_required');req.parentSession=s;next();}catch(e){next(e)}}
async function childAuth(req,res,next){try{const s=await session(req,'child');if(!s?.child_id||s.status!=='active')return fail(res,401,'child_auth_required');req.childSession=s;next();}catch(e){next(e)}}
const email=z.string().email().max(254),password=z.string().min(12).max(128),pin=z.string().regex(/^\d{6}$/);
app.get('/api/health',async(_q,res,next)=>{try{res.json({ok:await healthcheck()})}catch(e){next(e)}});

app.post('/api/parent/register',authLimiter,async(req,res,next)=>{try{if(production&&!mailerReady())return fail(res,503,'email_service_unavailable');const p=z.object({email,password,terms_accepted:z.literal(true),marketing_opt_in:z.boolean().optional().default(false)}).safeParse(req.body);if(!p.success)return fail(res,400,'invalid_registration');const e=normalizeEmail(p.data.email);if((await query('SELECT 1 FROM parents WHERE email=$1',[e])).rowCount)return fail(res,409,'account_exists');const ph=await hashPassword(p.data.password);let parent=null;for(let i=0;i<6&&!parent;i++){try{parent=(await query(`INSERT INTO parents(email,password_hash,family_code,marketing_opt_in) VALUES($1,$2,$3,$4) RETURNING id,email`,[e,ph,familyCode(),p.data.marketing_opt_in])).rows[0]}catch(err){if(err.code!=='23505')throw err}}if(!parent)return fail(res,500,'family_code_generation_failed');await withContext({parentId:parent.id},async client=>client.query(`INSERT INTO consents(parent_id,kind,text_version,granted) VALUES($1,'terms_privacy','2026-09',TRUE)`,[parent.id]));const tok=randomToken();await query(`INSERT INTO auth_tokens(parent_id,purpose,token_hash,expires_at) VALUES($1,'verify_email',$2,NOW()+INTERVAL '24 hours')`,[parent.id,tokenHash(tok)]);const dev=await sendVerificationEmail(parent.email,tok);res.status(201).json({ok:true,message:'verification_required',...(production?{}:{dev_verification_url:dev})});}catch(e){next(e)}});
app.post('/api/parent/resend-verification',authLimiter,async(req,res,next)=>{try{if(production&&!mailerReady())return fail(res,503,'email_service_unavailable');const p=z.object({email}).safeParse(req.body);if(p.success){const r=await query('SELECT id,email,verified_at FROM parents WHERE email=$1',[normalizeEmail(p.data.email)]),u=r.rows[0];if(u&&!u.verified_at){await query("DELETE FROM auth_tokens WHERE parent_id=$1 AND purpose='verify_email'",[u.id]);const tok=randomToken();await query(`INSERT INTO auth_tokens(parent_id,purpose,token_hash,expires_at) VALUES($1,'verify_email',$2,NOW()+INTERVAL '24 hours')`,[u.id,tokenHash(tok)]);await sendVerificationEmail(u.email,tok)}}res.json({ok:true});}catch(e){next(e)}});
app.get('/api/parent/verify',authLimiter,async(req,res,next)=>{try{const tok=String(req.query.token||'');if(tok.length<20)return res.redirect('/compte.html?verify=invalid');const r=await query(`SELECT id,parent_id FROM auth_tokens WHERE purpose='verify_email' AND token_hash=$1 AND used_at IS NULL AND expires_at>NOW() LIMIT 1`,[tokenHash(tok)]),row=r.rows[0];if(!row)return res.redirect('/compte.html?verify=invalid');await query('UPDATE parents SET verified_at=COALESCE(verified_at,NOW()),updated_at=NOW() WHERE id=$1',[row.parent_id]);await query('UPDATE auth_tokens SET used_at=NOW() WHERE id=$1',[row.id]);await createSession('parent',res,row.parent_id,null);res.redirect('/parents.html?verified=1');}catch(e){next(e)}});
app.post('/api/parent/login',authLimiter,async(req,res,next)=>{try{const p=z.object({email,password:z.string().min(1).max(128)}).safeParse(req.body);if(!p.success)return fail(res,400,'invalid_credentials');const r=await query('SELECT id,password_hash,verified_at FROM parents WHERE email=$1',[normalizeEmail(p.data.email)]),u=r.rows[0];if(!u||!(await verifyPassword(u.password_hash,p.data.password)))return fail(res,401,'invalid_credentials');if(!u.verified_at)return fail(res,403,'email_not_verified');await createSession('parent',res,u.id,null);res.json({ok:true});}catch(e){next(e)}});
app.post('/api/parent/logout',parentAuth,csrf('parent'),async(req,res,next)=>{try{const tok=req.cookies[PC];if(tok)await query("DELETE FROM sessions WHERE session_type='parent' AND token_hash=$1",[tokenHash(tok)]);res.clearCookie(PC,{path:'/'});res.clearCookie(PX,{path:'/'});res.json({ok:true});}catch(e){next(e)}});
app.get('/api/parent/me',parentAuth,(req,res)=>{const s=req.parentSession;res.json({ok:true,parent:{email:s.email,family_code:s.family_code,verified:Boolean(s.verified_at),marketing_opt_in:Boolean(s.marketing_opt_in)}})});
app.patch('/api/parent/preferences',parentAuth,csrf('parent'),async(req,res,next)=>{try{const p=z.object({marketing_opt_in:z.boolean()}).safeParse(req.body);if(!p.success)return fail(res,400,'invalid_preferences');await query('UPDATE parents SET marketing_opt_in=$1,updated_at=NOW() WHERE id=$2',[p.data.marketing_opt_in,req.parentSession.parent_id]);res.json({ok:true});}catch(e){next(e)}});
app.post('/api/parent/password-reset/request',authLimiter,async(req,res,next)=>{try{if(production&&!mailerReady())return fail(res,503,'email_service_unavailable');const p=z.object({email}).safeParse(req.body);if(p.success){const r=await query('SELECT id,email FROM parents WHERE email=$1',[normalizeEmail(p.data.email)]),u=r.rows[0];if(u){await query("DELETE FROM auth_tokens WHERE parent_id=$1 AND purpose='password_reset'",[u.id]);const tok=randomToken();await query(`INSERT INTO auth_tokens(parent_id,purpose,token_hash,expires_at) VALUES($1,'password_reset',$2,NOW()+INTERVAL '1 hour')`,[u.id,tokenHash(tok)]);const dev=await sendPasswordResetEmail(u.email,tok);if(!production)return res.json({ok:true,dev_reset_url:dev})}}res.json({ok:true});}catch(e){next(e)}});
app.post('/api/parent/password-reset/confirm',authLimiter,async(req,res,next)=>{try{const p=z.object({token:z.string().min(20).max(200),password}).safeParse(req.body);if(!p.success)return fail(res,400,'invalid_reset');const r=await query(`SELECT id,parent_id FROM auth_tokens WHERE purpose='password_reset' AND token_hash=$1 AND used_at IS NULL AND expires_at>NOW() LIMIT 1`,[tokenHash(p.data.token)]),row=r.rows[0];if(!row)return fail(res,400,'invalid_reset');await query('UPDATE parents SET password_hash=$1,updated_at=NOW() WHERE id=$2',[await hashPassword(p.data.password),row.parent_id]);await query('UPDATE auth_tokens SET used_at=NOW() WHERE id=$1',[row.id]);await query('DELETE FROM sessions WHERE parent_id=$1',[row.parent_id]);res.json({ok:true});}catch(e){next(e)}});
app.get('/api/parent/children',parentAuth,async(req,res,next)=>{try{const id=req.parentSession.parent_id,rows=await withContext({parentId:id},async c=>(await c.query('SELECT id,nickname,age_group,hero,status,ai_enabled,daily_minutes,created_at,approved_at FROM children ORDER BY created_at DESC')).rows);res.json({ok:true,children:rows});}catch(e){next(e)}});
app.patch('/api/parent/children/:id/approve',parentAuth,csrf('parent'),async(req,res,next)=>{try{const id=Number(req.params.id);if(!Number.isSafeInteger(id))return fail(res,400,'invalid_child');const row=await withContext({parentId:req.parentSession.parent_id},async c=>(await c.query("UPDATE children SET status='active',approved_at=COALESCE(approved_at,NOW()),updated_at=NOW() WHERE id=$1 RETURNING id,status",[id])).rows[0]);if(!row)return fail(res,404,'child_not_found');res.json({ok:true,child:row});}catch(e){next(e)}});
app.patch('/api/parent/children/:id/settings',parentAuth,csrf('parent'),async(req,res,next)=>{try{const id=Number(req.params.id),p=z.object({ai_enabled:z.boolean().optional(),daily_minutes:z.number().int().min(10).max(180).optional()}).refine(v=>Object.keys(v).length>0).safeParse(req.body);if(!Number.isSafeInteger(id)||!p.success)return fail(res,400,'invalid_settings');const row=await withContext({parentId:req.parentSession.parent_id},async c=>{const old=(await c.query('SELECT id,ai_enabled,daily_minutes FROM children WHERE id=$1',[id])).rows[0];if(!old)return null;const ai=p.data.ai_enabled??old.ai_enabled,min=p.data.daily_minutes??old.daily_minutes;const out=(await c.query('UPDATE children SET ai_enabled=$1,daily_minutes=$2,updated_at=NOW() WHERE id=$3 RETURNING id,ai_enabled,daily_minutes',[ai,min,id])).rows[0];if(p.data.ai_enabled===true)await c.query(`INSERT INTO consents(parent_id,child_id,kind,text_version,granted) VALUES($1,$2,'ai_chat','2026-09',TRUE)`,[req.parentSession.parent_id,id]);return out});if(!row)return fail(res,404,'child_not_found');res.json({ok:true,child:row});}catch(e){next(e)}});
app.delete('/api/parent/children/:id',parentAuth,csrf('parent'),async(req,res,next)=>{try{const id=Number(req.params.id);if(!Number.isSafeInteger(id))return fail(res,400,'invalid_child');const row=await withContext({parentId:req.parentSession.parent_id},async c=>(await c.query('DELETE FROM children WHERE id=$1 RETURNING id',[id])).rows[0]);if(!row)return fail(res,404,'child_not_found');res.json({ok:true});}catch(e){next(e)}});
app.get('/api/parent/export',parentAuth,async(req,res,next)=>{try{const id=req.parentSession.parent_id,parent=(await query('SELECT email,family_code,marketing_opt_in,created_at,verified_at FROM parents WHERE id=$1',[id])).rows[0];const d=await withContext({parentId:id},async c=>({children:(await c.query('SELECT id,nickname,age_group,hero,status,ai_enabled,daily_minutes,created_at FROM children ORDER BY id')).rows,progress:(await c.query('SELECT child_id,activity_key,score,stars,updated_at FROM progress ORDER BY child_id,activity_key')).rows,favorites:(await c.query('SELECT child_id,content_type,content_key,created_at FROM favorites ORDER BY child_id')).rows,consents:(await c.query('SELECT child_id,kind,text_version,granted,created_at FROM consents ORDER BY created_at')).rows}));res.setHeader('Content-Disposition','attachment; filename="mes-donnees.json"');res.json({exported_at:new Date().toISOString(),parent,...d});}catch(e){next(e)}});
app.delete('/api/parent/account',parentAuth,csrf('parent'),async(req,res,next)=>{try{const p=z.object({password:z.string().min(1).max(128)}).safeParse(req.body);if(!p.success)return fail(res,400,'password_required');const id=req.parentSession.parent_id,r=await query('SELECT password_hash FROM parents WHERE id=$1',[id]);if(!r.rows[0]||!(await verifyPassword(r.rows[0].password_hash,p.data.password)))return fail(res,401,'invalid_credentials');await query('DELETE FROM parents WHERE id=$1',[id]);[PC,PX,CC,CX].forEach(n=>res.clearCookie(n,{path:'/'}));res.json({ok:true});}catch(e){next(e)}});

app.post('/api/child/request',childLimiter,async(req,res,next)=>{try{const p=z.object({family_code:z.string().min(6).max(12),nickname:z.string().min(2).max(24),age_group:z.enum(['5-7','8-10','11-13','14-17']),hero:z.enum(['Lion','Taupe','Rihno']),pin}).safeParse(req.body);if(!p.success||!nicknameIsSafe(p.data?.nickname||''))return fail(res,400,'invalid_child_profile');const pr=await query('SELECT id,verified_at FROM parents WHERE family_code=$1',[normalizeFamilyCode(p.data.family_code)]),parent=pr.rows[0];if(!parent?.verified_at)return fail(res,404,'family_not_found');const count=await withContext({parentId:parent.id},async c=>Number((await c.query('SELECT COUNT(*) AS n FROM children')).rows[0].n));if(count>=8)return fail(res,409,'family_profile_limit');const nick=normalizeNickname(p.data.nickname);try{const child=await withContext({parentId:parent.id},async c=>(await c.query(`INSERT INTO children(parent_id,nickname,nickname_key,age_group,hero,pin_hash,status,created_by_child) VALUES($1,$2,LOWER($2),$3,$4,$5,'pending',TRUE) RETURNING id,nickname,status`,[parent.id,nick,p.data.age_group,p.data.hero,await hashPin(p.data.pin)])).rows[0]);res.status(201).json({ok:true,child,message:'pending_parent_approval'});}catch(err){if(err.code==='23505')return fail(res,409,'nickname_already_used');throw err}}catch(e){next(e)}});
app.post('/api/child/login',authLimiter,async(req,res,next)=>{try{const p=z.object({family_code:z.string().min(6).max(12),nickname:z.string().min(2).max(24),pin}).safeParse(req.body);if(!p.success)return fail(res,400,'invalid_credentials');const pr=await query('SELECT id FROM parents WHERE family_code=$1',[normalizeFamilyCode(p.data.family_code)]),parent=pr.rows[0];if(!parent)return fail(res,401,'invalid_credentials');const c=await withContext({parentId:parent.id},async db=>(await db.query('SELECT id,pin_hash,status FROM children WHERE nickname_key=$1 LIMIT 1',[normalizeNickname(p.data.nickname).toLowerCase()])).rows[0]);if(!c||!(await verifyPin(c.pin_hash,p.data.pin)))return fail(res,401,'invalid_credentials');if(c.status!=='active')return fail(res,403,'child_pending_approval');await createSession('child',res,null,c.id);res.json({ok:true});}catch(e){next(e)}});
app.post('/api/child/logout',childAuth,csrf('child'),async(req,res,next)=>{try{const tok=req.cookies[CC];if(tok)await query("DELETE FROM sessions WHERE session_type='child' AND token_hash=$1",[tokenHash(tok)]);res.clearCookie(CC,{path:'/'});res.clearCookie(CX,{path:'/'});res.json({ok:true});}catch(e){next(e)}});
app.get('/api/child/me',childAuth,(req,res)=>{const s=req.childSession;res.json({ok:true,child:{nickname:s.nickname,age_group:s.age_group,hero:s.hero,ai_enabled:Boolean(s.ai_enabled)}})});
app.post('/api/progress',childAuth,csrf('child'),async(req,res,next)=>{try{const p=z.object({activity_key:z.string().regex(/^[a-z0-9_-]{2,64}$/),score:z.number().int().min(0).max(1e6),stars:z.number().int().min(0).max(5)}).safeParse(req.body);if(!p.success)return fail(res,400,'invalid_progress');await withContext({childId:req.childSession.child_id},async c=>c.query(`INSERT INTO progress(child_id,activity_key,score,stars) VALUES($1,$2,$3,$4) ON CONFLICT(child_id,activity_key) DO UPDATE SET score=GREATEST(progress.score,EXCLUDED.score),stars=GREATEST(progress.stars,EXCLUDED.stars),updated_at=NOW()`,[req.childSession.child_id,p.data.activity_key,p.data.score,p.data.stars]));res.json({ok:true});}catch(e){next(e)}});
app.get('/api/progress',childAuth,async(req,res,next)=>{try{const rows=await withContext({childId:req.childSession.child_id},async c=>(await c.query('SELECT activity_key,score,stars,updated_at FROM progress ORDER BY updated_at DESC')).rows);res.json({ok:true,progress:rows});}catch(e){next(e)}});
app.post('/api/favorites',childAuth,csrf('child'),async(req,res,next)=>{try{const p=z.object({content_type:z.enum(['game','clip','story']),content_key:z.string().regex(/^[a-z0-9_-]{2,64}$/)}).safeParse(req.body);if(!p.success)return fail(res,400,'invalid_favorite');await withContext({childId:req.childSession.child_id},async c=>c.query('INSERT INTO favorites(child_id,content_type,content_key) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[req.childSession.child_id,p.data.content_type,p.data.content_key]));res.json({ok:true});}catch(e){next(e)}});
app.get('/api/favorites',childAuth,async(req,res,next)=>{try{const rows=await withContext({childId:req.childSession.child_id},async c=>(await c.query('SELECT content_type,content_key,created_at FROM favorites ORDER BY created_at DESC')).rows);res.json({ok:true,favorites:rows});}catch(e){next(e)}});
app.post('/api/chat',chatLimiter,childAuth,csrf('child'),async(req,res,next)=>{try{const p=z.object({hero:z.enum(['Lion','Taupe','Rihno']),message:z.string().min(1).max(280)}).safeParse(req.body);if(!p.success)return fail(res,400,'invalid_chat');const s=req.childSession;if(!s.ai_enabled)return fail(res,403,'ai_parental_activation_required');const r=await childSafeReply({hero:p.data.hero,ageGroup:s.age_group,message:p.data.message});if(!r.available)return fail(res,503,'ai_unavailable');res.json({ok:true,reply:r.text,blocked:Boolean(r.blocked)});}catch(e){next(e)}});
app.use('/api',(_q,res)=>fail(res,404,'not_found'));
app.use((err,_q,res,_n)=>{console.error('[api]',err?.message||err);if(!res.headersSent)fail(res,500,'server_error')});
setInterval(()=>cleanupExpired().catch(e=>console.error('[cleanup]',e.message)),3600000).unref();
app.listen(port,'0.0.0.0',()=>console.log(`[api] listening on ${port}`));
